// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARsvQopPIJ0jKuN2FYheG-siSm7EG6Kcc',
    appId: '1:395401843957:ios:6db3f300e8df86a2d721bc',
    messagingSenderId: '395401843957',
    projectId: 'bmi-calculator-cae46',
    storageBucket: 'bmi-calculator-cae46.firebasestorage.app',
    iosBundleId: 'com.funsoltechnologies.bmi.calculator.fat.weightloss.tracker.app',
  );
}
